version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: nosql1h25-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: always
